sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- mkdir -p $HOME/R/libs/
- echo 'R_LIBS_USER="$HOME/R/libs"' >  $HOME/.Renviron
- sudo apt-get install r-base
- R -e 'install.packages("packrat", "/home/travis/R/libs", repos="http://cran.us.r-project.org");'
- R -e 'packrat::restore(project = "/r-scripts");'
- npm update
install:
- npm install
script:
- npm test