sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- mkdir -p /home/travis/R/libs/
- echo 'R_LIBS_USER="/home/travis/R/libs"' >  /home/travis/.Renviron
- export R_LIBS_USER="/home/travis/R/libs"
- sudo apt-get install r-base
- R -e 'install.packages("packrat", "/home/travis/R/libs", repos="http://cran.us.r-project.org");'
- R -e 'packrat::restore(project = "/home/travis/r-scripts");'
- npm update
install:
- npm install
script:
- npm test