sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/r-scripts/packrat/src
    - $TRAVIS_BUILD_DIR/r-scripts/packrat/lib
    - node_modules
before_install:
- mkdir -p $TRAVIS_BUILD_DIR/R/libs/
- echo 'R_LIBS_USER="${TRAVIS_BUILD_DIR}/R/libs"' >  ${TRAVIS_BUILD_DIR}/.Renviron
- export R_LIBS_USER="${TRAVIS_BUILD_DIR}/R/libs"
- sudo apt-get install r-base
# - R -e "install.packages('packrat', '${TRAVIS_BUILD_DIR}/R/libs', repos='http://cran.us.r-project.org');"
- cd ${TRAVIS_BUILD_DIR}/r-scripts
- R -e "0" --args --bootstrap-packrat
- R -e "packrat::restore(project = '${TRAVIS_BUILD_DIR}/r-scripts', prompt = FALSE, overwrite.dirty = TRUE, restart = FALSE);"
- cd ${TRAVIS_BUILD_DIR}
- npm update
install:
- npm install
script:
- npm test