sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- mkdir -p ${TRAVIS_BUILD_DIR}/R/libs/
- echo 'R_LIBS_USER="${TRAVIS_BUILD_DIR}/R/libs"' >  ${TRAVIS_BUILD_DIR}/.Renviron
- export R_LIBS_USER="${TRAVIS_BUILD_DIR}/R/libs"
- sudo apt-get install r-base
- R -e "install.packages('packrat', '${TRAVIS_BUILD_DIR}/R/libs', repos='http://cran.us.r-project.org');"
- R -e "packrat::restore(project = '${TRAVIS_BUILD_DIR}/r-scripts');"
- npm update
install:
- npm install
script:
- npm test