sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master

# https://github.com/jtilly/R-travis-container-example/blob/master/.travis.yml
# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/)
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/r-scripts/packrat/src
    - $TRAVIS_BUILD_DIR/r-scripts/packrat/lib
    - $TRAVIS_BUILD_DIR/Rlibs/
    - node_modules
before_install:
- mkdir -p $TRAVIS_BUILD_DIR/Rlibs/
- echo "R_LIBS=${TRAVIS_BUILD_DIR}" > .Renviron
- echo 'R_LIBS_USER="${TRAVIS_BUILD_DIR}/Rlibs"' >>  ".Renviron"
- export R_LIBS_USER="${TRAVIS_BUILD_DIR}/Rlibs"
# - sudo apt-get install r-base
# - R -e "install.packages('packrat', '${TRAVIS_BUILD_DIR}/Rlibs', repos='http://cran.us.r-project.org');"
- cd ${TRAVIS_BUILD_DIR}/r-scripts
- R -e "0" --args --bootstrap-packrat
- R -e "packrat::restore(project = '${TRAVIS_BUILD_DIR}/r-scripts', prompt = FALSE, overwrite.dirty = TRUE, restart = FALSE);"
- cd ${TRAVIS_BUILD_DIR}
- npm update
install:
- npm install
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT