sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- apt-get install r-base
- R -e 'install.packages("packrat");'
- R -e 'packrat::restore(project = "/r-scripts");'
- npm update
install:
- npm install
script:
- npm test